version: '1.0.{build}'
configuration:
- Debug
- Release
platform: Any CPU
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
before_build:
- appveyor-retry dotnet restore "src\Servicem8.API\Servicem8.API.csproj" -v Minimal
build_script:
- dotnet build "src\Servicem8.API\Servicem8.API.csproj" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
artifacts:
- path: artifacts\**\*.*
cache:
- '%USERPROFILE%\.nuget\packages'